### PR TITLE
Add Yoruba

### PR DESCRIPTION
**Pull request by AbuTuraab**
I have added the Nigerian pidgin english translation of the EFP App here.

adenijialiyu.eth is my ENS name and aliyulekan@gmail.com is my email.

### CODE REVIEW

**Comment by AbuTuraab** [comment]
I have added the Nigerian Yoruba Language translation of the EFP App here. adenijialiyu.eth is my ENS name and aliyulekan@gmail.com is my email.

**Comment by AbuTuraab** [comment]
Hi @brantlymillegan  I have made a pull request for Nigerian pidgin English since yesterday, and I made another one for yoruba language today, did you get it please.?

**Comment by brantlymillegan** [comment]
> Hi @brantlymillegan I have made a pull request for Nigerian pidgin English since yesterday, and I made another one for yoruba language today, did you get it please.?

hey, thanks for submitting! I definitely saw it and will get to it soon

**Comment by brantlymillegan** [comment]
@AbuTuraab thanks for submitting! We already got a Nigerian Pidgin translation, so I've removed that from this pull request. Feel free to submit corrections/improvements to the other Nigerian Pidgin PR (or make your own PR when we merge it)

Your Yoruba translation looks great, and we'll take it! I'll send you your rewards soon after we merge it (soon)

@encryptedDegen use flag of Nigeria for this one too

**Comment by AbuTuraab** [comment]
Alright @brantlymillegan , thank you.

I'm glad to contribute to the project, I hope to make more contributions going forward.

**Pull request merged**
