### PR TITLE
Add Dutch

### PR DESCRIPTION
**Pull request by DeBelg**
Dutch translation.

Some minor confirmations needed to assure validity on website;

Translation

73;  Which context will this be used? It’s important as the grammar will be different

96; 97;106 similar

### CODE REVIEW

**Comment by DeBelg** [comment]
ENS:

foragers.eth

**Comment by encryptedDegen** [comment]
> Dutch translation.
> 
> Some minor confirmations needed to assure validity on website;
> 
> Translation
> 
> 73;  Which context will this be used? It’s important as the grammar will be different
> 
> 96; 97;106 similar

Hey @DeBelg thanks for submitting the translation file. To answer your questions:
- line 73: adding items to cart
- line 96: importing followings from another social app
- line 97: enter id into an input
- line 106: initiate a transaction

change your translations if needed and let me know if they are finished.
Thanks you!

**Comment by DeBelg** [comment]
> 

Done!

**Comment by brantlymillegan** [comment]
@DeBelg looks great! Once we merge it, I'll send you your bounty. Also, can you email me at brantly@ethfollow.xyz so I can send you your poap claim link

**Pull request merged**
