### PR TITLE
Add Hindi & Punjabi (IN)

### PR DESCRIPTION
**Pull request by prabhchintan**
Two-for-one: Punjabi and Hindi translations!

Randhawa.eth

### CODE REVIEW

**Comment by brantlymillegan** [comment]
@prabhchintan Great thanks! Question: Would it make sense for us to use the flag of India for Hindi, and the flag of Pakistan for Punjabi? I'm aware that Punjabi is spoken in both Pakistan and India, and that Urdu is the official language of Pakistan. So even while it's not perfect, I'm wondering if you think this is acceptable?

**Comment by prabhchintan** [comment]
India : 🇮🇳 : Hindi :: Pakistan : 🇵🇰 : Urdu

**Comment by brantlymillegan** [comment]
@encryptedDegen let's use the flag of India for both Hindi and Punjabi (IN) (be sure to include the (IN))

**Review by prabhchintan — COMMENTED** [review]
Looks good!

**Pull request merged**
